# Generated by Django 5.1 on 2024-08-27 21:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='news_post',
            options={'verbose_name': 'Новость', 'verbose_name_plural': 'Новости'},
        ),
        migrations.AddField(
            model_name='news_post',
            name='user_name',
            field=models.CharField(default='Default User', max_length=100, verbose_name='Имя пользователя'),
            preserve_default=False,
        ),
    ]
